#
#Makefile for misc devices that really don't fit anywhere else.
#
#

obj-y += hx8379c_wvga_dsi_vdo_rook.o

ccflags-$(CONFIG_MTK_LCM) += -I$(srctree)/drivers/misc/mediatek/lcm/inc \
			     -I$(srctree)/drivers/misc/mediatek/video/$(MTK_PLATFORM)/dispsys/

